/**************************************************************************************************
 *
 * NXP Confidential Proprietary
 *
 * Copyright 2022 NXP
 * All Rights Reserved
 *
 *****************************************************************************
 *
 * NXP Confidential and Proprietary. This software is owned or controlled by NXP and
 * may only be used strictly in accordance with the applicable license terms.  By
 * expressly accepting such terms or by downloading, installing, activating and/or
 * otherwise using the software, you are agreeing that you have read, and that you
 * agree to comply with and are bound by, such license terms.  If you do not agree to
 * be bound by the applicable license terms, then you may not retain, install, activate or
 * otherwise use the software.
 *
 **************************************************************************************************/

/******************************************************************************
 *   Project              : RFE_abstract 2.0
 *   Platform             : S32R41
 *****************************************************************************/

/**
 * DO NOT EDIT THIS FILE, it contains definitions that have to be identical on
 * RFE-M7 and application processor side and specific for each processor.
 */

#ifndef RFE_CMD_INTERFACE_H
#define RFE_CMD_INTERFACE_H


/******************************************************************************
 *                              INCLUDES
 *****************************************************************************/



/******************************************************************************
 *                              TYPES
 *****************************************************************************/

/******************************************************************************
 * User adjustable settings
 *****************************************************************************/

/**
 * Count of 32 Bit words for Command structure. The response structure will get the same length.
 * So the total length of the command response structure is rfeCmdServer_CMDRSPLEN*2*4. 
 * The payload length that the command server supports is adjusted by it.
 * Example: For 64 as value, 512 bytes of length is required in the window.
 */
#define RFE_CMD_IF_CMDRSPLEN                (64UL)

/**
 * The count of SharedData locations.
 * Shared Data is a mechanism where RFE-M7 can write values to shared memory that can be read from
 * the application processor.
 * The number defines these shared memory locations.
 * DO NOT EDIT THIS VALUE - it has to be identical on cmd server and client side.
 */
#define RFE_CMD_IF_SHAREDATACOUNT           (8UL)

/******************************************************************************
 * Non user adjustable settings (don't touch!)
 *****************************************************************************/

/**
 * The bit to set in the response opcode when a response is returned
 */
#define RFE_CMD_IF_RESPONSEBITMASK          (1UL << 31U)


/* Calculated / fixed settings */

/*
 * Offset definitions for command and response section
 */
#define RFE_CMD_IF_OFF_CNT                  (0UL)
#define RFE_CMD_IF_OFF_ID                   (1UL)
#define RFE_CMD_IF_OFF_LEN                  (2UL)
#define RFE_CMD_IF_OFF_DAT                  (3UL)
#define RFE_CMD_IF_OFF_CRC                  (RFE_CMD_IF_CMDRSPLEN - 1UL)

/**
 * Maximum command payload length  [Bytes]
 */
#define RFE_CMD_IF_MAXDATLEN                ((RFE_CMD_IF_CMDRSPLEN - 4UL) * 4UL)


#define RFE_CMD_IF_OFF_SHAREDATA            (2UL * RFE_CMD_IF_CMDRSPLEN)

typedef enum
{
    rfeCmdServer_cmdId_configure_e = 0U,
    rfeCmdServer_cmdId_radarCycleStart_e,
    rfeCmdServer_cmdId_radarCycleStop_e,    
    rfeCmdServer_cmdId_getFuSaFaults_e,
    rfeCmdServer_cmdId_getTime_e,        
    rfeCmdServer_cmdId_getVersion_e,
    rfeCmdServer_cmdId_monitorRead_e,
    rfeCmdServer_cmdId_getNextRadarCycleStartTime_e,
    rfeCmdServer_cmdId_setNextRadarCycleStartTime_e,
    rfeCmdServer_cmdId_updatePush_e,
    rfeCmdServer_cmdId_testContinuousWaveTransmissionStart_e,
    rfeCmdServer_cmdId_testContinuousWaveTransmissionStop_e,    
    rfeCmdServer_cmdId_testSetParam_e,
    rfeCmdServer_cmdId_getFuSaFaultStatistics_e,
    rfeCmdServer_cmdId_getBistZeroHourReferenceData_e,
    rfeCmdServer_cmdId_testGetInternalError_e,
    rfeCmdServer_cmdId_setFrontEnd_e,
    rfeCmdServer_cmdId_getFrontEnd_e,
	rfeCmdServer_cmdId_registerDump_e,
    rfeCmdServer_cmdId_configureInterrupt_e,
    RFE_CMD_IF_CMD_COUNT        //The count of implemented server commands
} rfeCmdServer_cmdId_t;


#endif // !RFE_CMD_INTERFACE_H

