###############################################################################
#  Initialization file for "RSDK Trace Parser/Viewer"
###############################################################################
# RULES for writing this file:
#   Every line that begins with '#' is considered a comment.
#   Every blank line is avoided.
#   Uncommented lines set the parameters for the current config.
#   ALL parameters must be set.
###############################################################################

##-------------------- Configuration Parameters -------------------------------


#---------------------- Functional Parameters ---------------------------------

#Endianness     [little, big]:  endianess used to write .hex file
#E.g. RRU2 = 'big', RRM/LAX/R41 = 'little'
configOptions.endianness    = 'little';

#TimerFreq      [<value_MHz>]:	frequency of the timer used for timestamps
#E.g. RRU2 = 250, RRM_SA = 133, RRM_LIN = 1000, LAX = 400, S32R41 = 200, SAF85XX = 160
configOptions.timerFreq     = 160;


#-------------------- Output Display Parameters -------------------------------

#XlsHighlight	[true, false]:	highlight pair events in resulting xls file
configOptions.xlsHighlight  = false;

#MakePlots      [true, false]:	plot relevant data as figures
configOptions.makePlots     = false;

#SptSeparate	[true, false]:	plot separate piecharts & stats for spt jobs
configOptions.sptSeparate   = false;


#-------------------- Additional Data Parameters ------------------------------

#KernelTrace    [true, false]:  include or not data from kernel(if it exists)
configOptions.kernelTrace   = false;

#LaxTrace       [true, false]:	include or not data from LAX(if it exists)
configOptions.laxTrace      = false;

#LaxFile        [<file_name>]:  relative path to file containing the LAX trace data
configOptions.laxFile       = '../data/example/lax_trace_dump.hex';

#------------------------------- EOF ------------------------------------------